#!/usr/bin/env python3
"""Dependency-free health check for an exported portable agent workspace."""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
AGENT = ROOT / ".agent"
STOP_GATE_ENV = "AGENT_STOP_GATE_ENABLED"
ERRORS: list[str] = []
NOTES: list[str] = []


def fail(message: str) -> None:
    ERRORS.append(message)


def require(relative: str) -> Path:
    path = ROOT / relative
    if not path.is_file():
        fail(f"missing required file: {relative}")
    return path


def load_json(relative: str) -> object | None:
    path = require(relative)
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        fail(f"invalid JSON in {relative}: {exc}")
        return None


def is_vendored_dependency(path: Path) -> bool:
    """Return whether ``path`` is inside the third-party dependency snapshot."""
    return path.relative_to(ROOT).parts[:2] == ("harness", "vendor")


def find_bash() -> str | None:
    if os.name != "nt":
        return shutil.which("bash")
    roots = [os.environ.get("ProgramFiles"), os.environ.get("ProgramW6432"), os.environ.get("LocalAppData")]
    for root in roots:
        if not root:
            continue
        suffix = "Programs/Git/bin/bash.exe" if "AppData" in root else "Git/bin/bash.exe"
        candidate = Path(root) / suffix
        if candidate.is_file():
            return str(candidate)
    candidate = shutil.which("bash")
    if candidate and Path(candidate).resolve().as_posix().lower() != "c:/windows/system32/bash.exe":
        return candidate
    return None


def find_powershell() -> str | None:
    return shutil.which("powershell.exe") or shutil.which("pwsh")


def validate_inventory() -> None:
    for relative in (
        "AGENTS.md", "CLAUDE.md", "workspace-aid/README.md", ".gitignore",
        ".codex/config.toml", ".codex/hooks.json", ".claude/settings.json",
        ".agent/hooks.py", ".agent/hooks.ps1", ".agent/hooks.sh", ".agent/run-bounded.ps1",
        ".agent/run-bounded.sh", ".agent/stop-verify.ps1", ".agent/stop-verify.sh",
        ".agent/stop-verify.json.example", ".agent/verify.toml.example",
        ".agent/select-skillset.py", ".agent/skillsets.json",
    ):
        require(relative)
    if (ROOT / "for-jason.md").exists():
        fail("superseded planning document is present: for-jason.md")


def validate_artifact_hygiene() -> None:
    artifact_directories = {".agent-runtime", ".pytest_cache", "__pycache__"}
    for current, directories, files in os.walk(ROOT):
        current_path = Path(current)
        if is_vendored_dependency(current_path):
            directories.clear()
            continue
        if ".git" in directories:
            directories.remove(".git")
        for directory in list(directories):
            if directory in artifact_directories:
                fail(f"generated artifact directory is present: {(current_path / directory).relative_to(ROOT)}")
                directories.remove(directory)
        for filename in files:
            if filename.endswith((".pyc", ".pyo")):
                fail(f"generated bytecode is present: {(current_path / filename).relative_to(ROOT)}")


def validate_json_contracts() -> None:
    expected_events = {"SessionStart", "PreToolUse", "Stop"}
    for provider, relative in (("Codex", ".codex/hooks.json"), ("Claude", ".claude/settings.json")):
        document = load_json(relative)
        hooks = document.get("hooks") if isinstance(document, dict) else None
        if not isinstance(hooks, dict) or set(hooks) != expected_events:
            fail(f"{provider} hook events do not match {sorted(expected_events)}")

    stop_example = load_json(".agent/stop-verify.json.example")
    if not isinstance(stop_example, dict) or stop_example.get("enabled") is not False:
        fail(".agent/stop-verify.json.example must ship disabled")
    skillsets = load_json(".agent/skillsets.json")
    if not isinstance(skillsets, dict) or skillsets.get("schema") != "portable-skillsets/v1":
        fail(".agent/skillsets.json has the wrong schema")

    if (ROOT / ".agent/multi-agent.json").is_file():
        multi = load_json(".agent/multi-agent.json")
        if not isinstance(multi, dict) or multi.get("schema") != "portable-multi-agent/v2":
            fail(".agent/multi-agent.json has the wrong schema")
        else:
            agents = multi.get("agents")
            if not isinstance(agents, dict) or not agents:
                fail("multi-agent catalog has no agents")
            else:
                for name, entry in agents.items():
                    if not isinstance(entry, dict) or not isinstance(entry.get("command"), list):
                        fail(f"multi-agent entry {name!r} has no argument-vector command")
                        continue
                    for role in entry.get("roles", []):
                        require(f".agent/roles/{role}.md")
        for relative in (
            ".agent/multi_agent.py", ".agent/launch-agent.ps1", ".agent/launch-agent.sh",
            ".agent/pipe-prompt-file.ps1", ".agent/pipe-prompt-file.sh",
        ):
            require(relative)


def validate_stop_gate_scope() -> None:
    readers = {
        path.name
        for pattern in ("*.ps1", "*.sh")
        for path in AGENT.glob(pattern)
        if STOP_GATE_ENV in path.read_text(encoding="utf-8")
    }
    expected = {"stop-verify.ps1", "stop-verify.sh"}
    if readers != expected:
        fail(f"master Stop-gate switch readers are {sorted(readers)}, expected {sorted(expected)}")
    checks = ((".agent/stop-verify.ps1", 10), (".agent/stop-verify.sh", 6))
    for relative, line_count in checks:
        path = require(relative)
        if path.is_file() and STOP_GATE_ENV not in "\n".join(path.read_text(encoding="utf-8").splitlines()[:line_count]):
            fail(f"Stop-gate wrapper is not at the entry point: {relative}")


def validate_skill_mirror() -> None:
    canonical = ROOT / ".agents/skills"
    mirror = ROOT / ".claude/skills"
    canonical_files = {
        path.relative_to(canonical) for path in canonical.rglob("*")
        if path.is_file() and "agents" not in path.relative_to(canonical).parts
    }
    mirror_files = {path.relative_to(mirror) for path in mirror.rglob("*") if path.is_file()}
    if canonical_files != mirror_files:
        fail("Codex and Claude visible skill catalogs contain different files")
        return
    for relative in canonical_files:
        if (canonical / relative).read_bytes() != (mirror / relative).read_bytes():
            fail(f"Codex and Claude skill copies differ: {relative}")


def validate_source_files() -> None:
    for path in list(AGENT.glob("*.py")) + list((ROOT / ".agents/skills").rglob("*.py")):
        try:
            compile(path.read_text(encoding="utf-8"), str(path), "exec")
        except (OSError, UnicodeError, SyntaxError) as exc:
            fail(f"Python parse failed for {path.relative_to(ROOT)}: {exc}")

    bash = find_bash()
    if bash:
        for path in AGENT.glob("*.sh"):
            result = subprocess.run([bash, "-n", str(path)], capture_output=True, text=True, check=False)
            if result.returncode:
                fail(f"Bash parse failed for {path.relative_to(ROOT)}: {result.stderr.strip()}")
    else:
        NOTES.append("Bash syntax check skipped: native Bash/Git Bash was not found")

    powershell = find_powershell()
    if powershell:
        parser = (
            "$tokens=$null;$errors=$null;"
            "[System.Management.Automation.Language.Parser]::ParseFile($env:PORTABLE_VALIDATE_PS_TARGET,[ref]$tokens,[ref]$errors)|Out-Null;"
            "if($errors.Count){$errors|ForEach-Object{[Console]::Error.WriteLine($_)};exit 1}"
        )
        for path in AGENT.glob("*.ps1"):
            environment = os.environ.copy()
            environment["PORTABLE_VALIDATE_PS_TARGET"] = str(path)
            result = subprocess.run(
                [powershell, "-NoProfile", "-NonInteractive", "-Command", parser],
                capture_output=True, text=True, check=False, env=environment,
            )
            if result.returncode:
                fail(f"PowerShell parse failed for {path.relative_to(ROOT)}: {result.stderr.strip()}")
    else:
        NOTES.append("PowerShell syntax check skipped: PowerShell was not found")


def smoke_default_off_stop_gate() -> None:
    environment = os.environ.copy()
    environment.pop(STOP_GATE_ENV, None)
    invocations: list[tuple[str, list[str]]] = []
    bash = find_bash()
    if bash:
        invocations.append(("Bash", [bash, (AGENT / "stop-verify.sh").as_posix(), "stop"]))
    powershell = find_powershell()
    if powershell:
        invocations.append(
            (
                "PowerShell",
                [powershell, "-NoProfile", "-NonInteractive", "-File", str(AGENT / "stop-verify.ps1"), "stop"],
            )
        )
    for label, command in invocations:
        try:
            result = subprocess.run(
                command,
                input="not hook JSON",
                capture_output=True,
                text=True,
                check=False,
                env=environment,
                timeout=10,
            )
        except subprocess.TimeoutExpired:
            fail(f"{label} Stop gate did not exit promptly while disabled")
            continue
        if result.returncode != 0 or result.stdout or result.stderr:
            fail(f"{label} Stop gate is not a silent successful no-op by default")


def validate_portability() -> None:
    markers = ("C:" + "\\Users\\", "/" + "Users/", "/" + "home/")
    suffixes = {".json", ".md", ".ps1", ".py", ".sh", ".toml", ".txt", ".yaml", ".yml"}
    for current, directories, files in os.walk(ROOT):
        if ".git" in directories:
            directories.remove(".git")
        current_path = Path(current)
        if is_vendored_dependency(current_path):
            directories.clear()
            continue
        for filename in files:
            path = current_path / filename
            if path.suffix.lower() not in suffixes:
                continue
            try:
                content = path.read_text(encoding="utf-8")
            except UnicodeError:
                fail(f"text file is not UTF-8: {path.relative_to(ROOT)}")
                continue
            # A relative resource label such as provider/home/service is not an absolute path.
            if any(re.search(r"(?<![\w.-])" + re.escape(marker), content) for marker in markers):
                fail(f"user-specific absolute path marker found in {path.relative_to(ROOT)}")


def main() -> int:
    validate_inventory()
    validate_artifact_hygiene()
    validate_json_contracts()
    validate_stop_gate_scope()
    validate_skill_mirror()
    validate_source_files()
    smoke_default_off_stop_gate()
    validate_portability()
    for note in NOTES:
        print(f"SKIP: {note}")
    if ERRORS:
        for error in ERRORS:
            print(f"FAIL: {error}", file=sys.stderr)
        print(f"WORKSPACE VALIDATION FAILED ({len(ERRORS)} issue(s))", file=sys.stderr)
        return 1
    flavor = "multi-agent" if (ROOT / ".agent/multi-agent.json").is_file() else "generic"
    print(f"WORKSPACE VALIDATION PASSED ({flavor} export)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
